### ISSUE TITLE
Nobrainer Duplicate Tables

### ISSUE THREAD

**Issue by caspiano** [PlaceOS/auth#10]
Nobrainer generates duplicate tables.
We should patch the orm with something [like this](https://github.com/spider-gazelle/rethinkdb-orm/blob/master/src/rethinkdb-orm/connection.cr#L155)

This change should resolve place-labs/development-environment/issues/3

**Comment by caspiano** [comment]
[This is the method that needs patching](https://github.com/nviennot/nobrainer/blob/67681935e1d04cf5d6ee1a27348aaa6416b17fc1/lib/no_brainer/query_runner/table_on_demand.rb#L19)

**Comment by stakach** [comment]
fix in 45083489003da330dfa395c391f8e0690b3c2495
pull request at: https://github.com/nviennot/nobrainer/pull/260
