### ISSUE TITLE
OAuth2 callback URL incompatible with Azure AD B2C

### ISSUE THREAD

**Issue by kimburgess** [PlaceOS/auth#22]
Using Azure AD as an OAuth2 based IdP is currently not possible due to query parameters being disallowed in redirect URI's configured on Azure.

The [current callback URL format](https://github.com/PlaceOS/auth/blob/d1a6af63b1beafb426c1a7a2fdad68891e76cdf8/lib/omniauth/strategies/generic_oauth.rb#L79) encodes the provider id as a static query param.

This was [previously allowed](https://docs.microsoft.com/en-us/azure/active-directory/develop/reference-breaking-changes#redirect-uris-can-now-contain-query-string-parameters), but may have regressed as part of a [recent Azure service update](https://docs.microsoft.com/en-us/azure/active-directory/develop/reference-breaking-changes#empty-fragments-will-be-appended-to-every-http-redirect-from-the-login-endpoint).

To re-enable compatibility, without relying on an upstream update, there should be potential to support this as a [path parameter](https://github.com/PlaceOS/auth/blob/d1a6af63b1beafb426c1a7a2fdad68891e76cdf8/config/routes.rb#L11-L12).

---

Note: configuring as a SAML based IdP _is_ currently supported and is the recommended approach.

**Comment by w-le** [comment]
Yep upvoting this feature.

In the meantime, I had a similar issue when integrating azure ad saml with acaengine last year (not sure why they suddenly allowed query params in the callback uri again). This is a usable (tested OK) workaround at an nginx config level:

https://gitlab.com/aca-engine/deploy/setup/-/blob/master/roles/engine/files/config/nginx/nginx.conf#L133-137

**Comment by stakach** [comment]
nice, I think I mentioned this change to @kimburgess at the time
I think we might need to do it that way as I can't find a good way of getting around omniauth route expectations for SAML

I'll improve the regex there a bit, as need to support metadata route and we can go from there.

**Comment by stakach** [comment]
this should work for both adfs and oauth2 in placeos

```
location /auth/adfs/callback/adfs_strat- {
    rewrite ^/auth/adfs/callback/([^/]+)(.*)$ /auth/adfs/callback?id=$1&$args last;
}

location /auth/oauth2/callback/oauth_strat- {
    rewrite ^/auth/oauth2/callback/([^/]+)(.*)$ /auth/oauth2/callback?id=$1&$args last;
}
```

**Comment by kimburgess** [comment]
Could these go straight into [config/routes.rb](https://github.com/PlaceOS/auth/blob/master/config/routes.rb) to remove the need for an external re-write?

**Comment by stakach** [comment]
problem is omniauth runs before rails so have to match manually and nginx is faster than ruby

**Comment by kimburgess** [comment]
I'm having some issues trying to recreate this. Using a developer tenant it looks like the query param callbacks are supported for both localhost and public domains. Before we go making product level changes @w-le do you have any active examples of this in the wild?

![923C4299-C3CC-4D11-9556-95131831107D](https://user-images.githubusercontent.com/843652/111931981-231c7980-8b08-11eb-81d5-4e25cb7d7c8d.jpeg)

**Comment by w-le** [comment]
Nope I've never actually had to set up oauth2 with Azure before, only Saml2.
I think it was in 2018 when I saw 1 or 2 azure app registrations not allow query params in a saml 2 callback uri, which is what made me write that nginx uri reritw workaround. 
But just months later it appeared be supported again, so I haven't needed to use the workaround since.

I think it's highly likely that azure now just globally supports query params in their oauth2 callback uris. In that case we potentially may not need support path based callback uris.

I haven't seen path based uris required for any other saml2 idp that I've worked with, which have bee: okta, adfs, auth0

**Comment by kimburgess** [comment]
Took a deeper look on a site that reported this. This appears to impact Azure B2C only. Additional confirming here: https://stackoverflow.com/questions/66242163/redirect-uri-in-azure-b2c-with-query-string-error-detail-url-may-not-contain-a
