### ISSUE TITLE
Successful login redirects back to login page

### ISSUE THREAD

**Issue by w-le** [PlaceOS/auth#47]
**Describe the bug**
In development mode, with env var
`COAUTH_NO_SSL: "true"`
successful (202) logins will result in redirection back to the login page. Making it impossible to access the desired app (e.g. backoffice). This can be reproduced with partner-environment: https://github.com/place-labs/partner-environment/issues/85

**Comment by stakach** [comment]
Yeah that ENV == true means you are going to access the environment over HTTP not HTTPS
So it disables a bunch of security features

Given we always use HTTPS it should be set to `false`

**Comment by stakach** [comment]
it's there to overwrite security features enabled by `RAILS_ENV=development`'
i.e. `RAILS_ENV=development` == `COAUTH_NO_SSL=true` (by default)
i.e. `RAILS_ENV=production` == `COAUTH_NO_SSL=false` (by default)

but if you want to run `RAILS_ENV=development` over HTTPS then you need to set `COAUTH_NO_SSL=false`

**Comment by w-le** [comment]
ok i'll double check setting only COAUTH_NO_SSL=false in partner-environment, as per https://github.com/place-labs/partner-environment/pull/86#issuecomment-986837880
