### ISSUE TITLE
expired auth data should be deleted to prevent DB size growing indefinitely

### ISSUE THREAD

**Issue by w-le** [PlaceOS/auth#79]
`doorkeeper_grant` and `doorkeeper_token` tables grow without bound. 

Taking 50GB in this real world example:

![image](https://user-images.githubusercontent.com/10395560/186830284-46e21042-b241-4c2a-a35b-e1275010f8be.png)

**Comment by w-le** [comment]
part of the solution should include a migration in placeos/init that safely deletes expired auth objects

**Comment by stakach** [comment]
I think there must be some error occuring at usyd as access grants expire pretty fast

https://github.com/place-labs/doorkeeper-rethinkdb/blob/master/lib/support/orm/rethinkdb/access_grant.rb#L115

**Comment by chillfox** [comment]
looking at the db on the dev server, there is no ttl field on the grants.

`r.db('place_development').table('doorkeeper_grant')`

```
{

    "application_id": "..." ,
    "code_challenge": "..." ,
    "code_challenge_method": "S256" ,
    "created_at": Tue Mar 09 2021 10:49:37 GMT+00:00 ,
    "expires_in": 600 ,
    "id": "..." ,
    "redirect_uri": https://placeos-dev.aca.im/backoffice/oauth-resp.html, [»](https://placeos-dev.aca.im/backoffice/oauth-resp.html)
    "resource_owner_id": "..." ,
    "revoked_at": Tue Mar 09 2021 10:49:38 GMT+00:00 ,
    "scopes": "public" ,
    "token": "..." ,
    "updated_at": Tue Mar 09 2021 10:49:38 GMT+00:00
}
```

**Comment by stakach** [comment]
ahh, that'll probably be the issue then..

**Comment by chillfox** [comment]
Guess I can just copy this from doorkeeper-couchbase.

https://github.com/acaprojects/doorkeeper-couchbase/blob/534747e4e58c44805c99a6f2e746de6ffc5c4e59/lib/support/orm/couchbase/access_grant.rb#L37,L41

```
        # Lets make sure these keys are not clogging up the database forever
        def save(**options)
            options[:ttl] = self.created_at + self.expires_in + 30
            super(**options)
        end
```

**Comment by chillfox** [comment]
https://github.com/place-labs/doorkeeper-rethinkdb/pull/1

**Comment by chillfox** [comment]
https://github.com/PlaceOS/init/pull/74

**Comment by chillfox** [comment]
https://github.com/PlaceOS/auth/pull/81

**Comment by chillfox** [comment]
Looks like this is now working on the dev server.

Old records without a TTL have been deleted and new records have a TTL.

```
{
    "application_id": "..." ,
    "code_challenge": "..." ,
    "code_challenge_method": "S256" ,
    "created_at": Thu Sep 15 2022 03:28:14 GMT+00:00 ,
    "expires_in": 600 ,
    "id": "..." ,
    "redirect_uri": https://staytion-dev.aca.im/workplace/oauth-resp.html, »
    "resource_owner_id": "..." ,
    "revoked_at": Thu Sep 15 2022 03:28:14 GMT+00:00 ,
    "scopes": "public" ,
    "token": "..." ,
    "ttl": 1663212554 ,
    "updated_at": Thu Sep 15 2022 03:28:14 GMT+00:00
}
```

**Comment by stakach** [comment]
fixed and tested on nightly
